---
title: "Phytoplankton Background"
---

## What are Phytoplankton?

**Phytoplankton** are small organisms that can be found floating in most water bodies. They occur as unicellular forms (single cell), colonial forms (multiple cells in a clump), filaments (long chains of cells), or flagellates (having flagella that give them some mobility). Like plants, they are primary producers; they convert light energy from the sun and carbon dioxide into the living matter of their cells through photosynthesis. Phytoplankton from the San Francisco Estuary fall into four broad categories: cyanobacteria, diatoms, green algae, and various flagellate groups.

-   **Cyanobacteria** are the only phytoplankton that are true bacteria, meaning their cells’ internal structures do not have membranes around them. Often called blue-green algae due to their color, they have colonized nearly all freshwater, marine, and terrestrial habitats on earth. Some species can produce blooms and harmful toxins that degrade water quality.

-   **Diatoms** are unique among phytoplankton because they have a cell wall made of glass, or silicon dioxide, called a frustule. They can be unicellular or colonial. There are two main types of diatoms, centric and pennate.

-   **Green algae** are a large, diverse group of phytoplankton consisting of unicellular, filamentous, colonial, and flagellated forms. They are found in a wide variety of freshwater, marine, and terrestrial habitats. Some species can form nuisance blooms or surface scums in nutrient-rich water.

-   **Flagellates** include phytoplankton from many different groups, such as cryptophytes, dinoflagellates, chrysophytes, haptophytes, and euglenoids. Some flagellates, like cryptophytes, can be important as food for zooplankton. Some groups of flagellates, such as haptophytes and dinoflagellates, can produce toxic blooms that can kill or poison fish and invertebrates.

## Why are phytoplankton important?

Phytoplankton are the foundation of the aquatic food web. They feed a diverse array of organisms, ranging from microscopic zooplankton to large pelagic fish. Small fish and benthic organisms also graze on phytoplankton, and are in turn consumed by larger organisms such as birds. Because of their importance as the base of the food web, changes in phytoplankton in the San Francisco Estuary can have cascading effects throughout the food web. For example, loss of phytoplankton species that are important food sources can negatively affect the zooplankton and fish species that feed on those phytoplankton, and thus negatively affect the animals preying on those zooplankton and fish.

Phytoplankton can also affect elements of water quality such as pH, dissolved oxygen, taste and odor of drinking water, and water transparency. Large algal blooms, both toxic and non-toxic, can have adverse effects on the water quality parameters listed above. They can also have negative aesthetic effects by forming large, floating surface scums. Monitoring changes in phytoplankton can be useful in assessing water quality trends by detecting the presence of nuisance species or the development of large blooms that could require management action.

**Chlorophyll-a** is the primary photosynthetic product made by phytoplankton and plants, and gives them their green color. Chlorophyll-a is also a measure of the biomass that is directly available to organisms that prey on phytoplankton, such as clams and zooplankton.\
Sometimes the green color is masked by secondary pigments, and these phytoplankton often appear brown or red instead of green. Phytoplankton biomass and the resulting chloro¬phyll-a concentrations in some areas of the Estuary may be influenced by extensive filtration of the water column by the introduced Asian clam, Potamocorbula amurensis. Well-established benthic populations of P. amurensis in Suisun and San Pablo bays are thought to have contrib¬uted to the low chlorophyll-a concentrations (and increased water clarity) measured in these westerly bays since the mid-1980s. By removing phytoplankton from the water, P. amurensis has reduced the amount of phytoplankton available to other organisms such as zooplankton.

## How is phytoplankton monitored?

The California DWR Phytoplankton and Chlorophyll-a monitoring measures the composition (what kinds?), abundance (how many?), diversity (how many kinds?), and distribution (where are they?) of phytoplankton. It also measures phytoplankton biomass as chlorophyll-a; both types of monitoring are performed as part of the IEP’s Environmental Monitoring Program (EMP). Thirteen fixed sites are currently sampled for both phytoplankton and chlorophyll-a, with two additional sites sampled at variable locations based on bottom specific conductance of 2,000 and 6,000 micro-Siemens, respectively. Historically, samples were collected once or twice monthly at up to 33 sites. Phytoplankton and chlorophyll-a samples are collected monthly alongside the water quality and zooplankton sampling. Whole, unfiltered water samples are collected monthly from one meter below the surface to determine phytoplankton composition; Lugol’s solution is then added as a stain and preservative. For chlorophyll-a samples, water is filtered onto glass carbon fiber filters for analysis. Phytoplankton and chlorophyll-a data are available from 1975 to the present.

Changes in phytoplankton composition, abundance, diversity, distribution, and biomass are monitored throughout the San Francisco Estuary, from San Pablo Bay east through the upper Estuary to the mouths of the Sacramento, Mokelumne, and San Joaquin Rivers.

Because different phytoplankton species live in different parts of the Estuary, the sites represent a wide range of habitats of varying physical conditions, including wide ranges of salinity and temperature. Sites range from narrow, freshwater channels in the Delta to broad, estuarine bays.
