project:
  type: default
  output-dir: _pdf
  execute-dir: file

format:
  pdf:
    toc: false
    documentclass: article
    latex-engine: pdflatex
    number-sections: true
    includes:
      in-header: admin/styling_scripts/pdf-header.tex # Optional for custom headers
    header-includes:
      - \usepackage{fancyhdr}
      - \pagestyle{fancy}
      - \fancyhf{}
      - \fancyfoot[C]{\thepage}
