project:
  type: website
  output-dir: docs
  execute-dir: file
  
website:
  page-navigation: false
  title: 'Environmental Monitoring Program'
  favicon: admin/figures-tables/sentinel.ico
  
  page-footer:
    background: '#e8f1f5'
    center: |
        ![](/admin/figures-tables/EMP_footer.png){fig-alt="DWR, CDFW, and USBR logos" height=50px}

  navbar:
    background: '#e8f1f5'
    foreground: '#006699'
    logo: 'admin/figures-tables/EMP_logo.png'
    logo-alt: 'EMP logo'
    title: false
    collapse-below: lg
    left:
      - text: "Home"
        href: sections/general/qmd-files/index.qmd
      - text: "Data Links"
        href: sections/general/qmd-files/data-links.qmd
      - text: "Annual Reports"
        menu:
          - text: "Continuous Water Quality"
            href: sections/cwq/qmd-files/cwq-report.qmd
          - text: "Discrete Water Quality"
            href: sections/dwq/qmd-files/dwq-report.qmd
          - text: "Benthic Invertebrates"
            href: sections/benthic/qmd-files/benthic-report.qmd
          - text: "Phytoplankton"
            href: sections/phyto/qmd-files/phyto-report.qmd
          - text: "Zooplankton"
            href: sections/zoop/qmd-files/zoop-report.qmd
      - text: Special Studies
        menu:
          - text: "Veliger Monitoring Program"
            href: sections/special-studies/qmd-files/veliger-info.qmd
      - text: "Contact Us"
        href: "mailto:ted.flynn@water.ca.gov"

format:
  html:
    theme: cosmo
    css: [admin/styling_scripts/styles.css, admin/styling_scripts/slideshow.css]
    # grid:
    #   sidebar-width: 300px
    toc: true
    toc-title: Contents
    page-layout: full
    