project:
  type: website

website:
  page-navigation: false
  title: 'Environmental Monitoring Program'
  favicon: admin/figures/sentinel.ico
  
  page-footer:
    background: '#e8f1f5'
    center: |
        ![](/admin/figures/usbr-logo.jpg){fig-alt="USBR logo" width=50px height=50px}
        ![](/admin/figures/dwr-logo.png){fig-alt="DWR logo" width=50px height=50px}
        ![](/admin/figures/iep-logo.jpg){fig-alt="IEP logo" width=50px height=50px}
        ![](/admin/figures/cdfw-logo.png){fig-alt="CDFW logo" width=50px height=50px}

  navbar:
    background: '#e8f1f5'
    foreground: '#006699'
    logo: 'admin/figures/EMP-logo-website-small-3.png'
    logo-alt: 'EMP logo'
    title: false
    collapse-below: lg
    left:
      - text: "Home"
        href: sections/general/Rmd-files/index.qmd
      - text: "Data Links"
        href: "https://github.com/quarto-dev/quarto-cli/discussions"
      - text: "Annual Reports"
        menu:
          - text: "Continuous Water Quality"
            href: sections/c-wq/Rmd-files/00-cwq-info.qmd
          - text: "Discrete Water Quality"
            href: sections/d-wq/Rmd-files/00-dwq-info.qmd
          - text: "Benthic Invertebrates"
            href: "https://github.com/quarto-dev/quarto-cli/discussions"
          - text: "Phytoplankton"
            href: "https://github.com/quarto-dev/quarto-cli/discussions"
          - text: "Zooplankton"
            href: "https://github.com/quarto-dev/quarto-cli/discussions"
      - text: Special Studies
        menu:
          - text: "Veliger Monitoring Program"
            href: "https://github.com/quarto-dev/quarto-cli/discussions"
      - text: "Contact Us"
        menu:
          - text: "General Questions"
            href: "https://github.com/quarto-dev/quarto-cli/issues"
          - text: "Website Help"
            href: "https://github.com/quarto-dev/quarto-cli/discussions"
    # right:
    #   - text: '![](admin/figures/usbr-logo.jpg)'
    

  sidebar:
    - id: landing
    
    - id: cwq
      collapse-level: 2
      contents:
        - section: "Continuous Water Quality"
          contents:
            - sections/c-wq/Rmd-files/00-cwq-info.qmd
            - text: "Current Report"
              href: sections/c-wq/Rmd-files/00-cwq-report.qmd
            - text: "Archived Reports"
              href: sections/c-wq/Rmd-files/00-cwq-archive.qmd

    - id: dwq
      collapse-level: 2
      contents:
        - section: "Discrete Water Quality"
          contents:
            - sections/d-wq/Rmd-files/00-dwq-info.qmd
            - text: "Current Report"
              href: sections/d-wq/Rmd-files/00-dwq-report.qmd
            - text: "Archived Reports"
              href: sections/d-wq/Rmd-files/00-dwq-archive.qmd

format:
  html:
    theme: cosmo
    css: [admin/html-css/styles.css, admin/html-css/slideshow.css] # 'https://use.fontawesome.com/releases/v5.14.0/css/all.css']
    # grid:
    #   sidebar-width: 300px
    toc: true
    toc-title: Contents
    page-layout: full
    

# filters:
#   - include-files.lua
#   - quarto
