---
title: "Zooplankton Background"
---

Zooplankton in the San Francisco Estuary (SFE) serve as a vital trophic link between aquatic primary producers and higher trophic level consumers. As primary consumers of phytoplankton, zooplankton facilitate the flow of carbon through a large and complex food web that historically supported abundant fisheries (Schroeter et al. 2015; Kimmerer et al. 2018). Zooplankton in the SFE are a key food source for endangered and threatened fish species, notably the Delta Smelt (Hypomesus transpacificus) and Longfin Smelt (Spirinchus thaleichthys) (Hobbs et al. 2006; Slater and Baxter 2014). Many species of fish, including Striped Bass (*Morone saxatilis*) and Chinook Salmon (*Oncorhynchus tshawytscha*) feed on zooplankton in the estuary as larvae and juveniles (Goertler et al. 2018; Heubach et al. 1963), while others like Tule Perch (*Hysterocarpus traskii*) and Prickly Sculpin (Cottus asper) include zooplankton in their diets throughout their lifetimes (Kimmerer 2006, Feyrer et al. 2003).

The importance of zooplankton in the estuarine food web prompted the implementation of the Zooplankton Study in 1972 to assess the prey resources available to fish in the upper SFE. Mandated by the State Water Resources Control Board’s Water Right Decision 1641, the study is conducted jointly by the California Department of Fish and Wildlife and the California Department of Water Resources under the guidance and management of the Interagency Ecological Program. For over five decades this study has monitored the zooplankton community in the region, tracking abundance trends and distribution patterns, detecting and monitoring introduced species, and documenting dramatic shifts in community composition. Changes in zooplankton abundance and composition have been linked to major declines in pelagic fishes in the upper estuary (Sommer et al. 2007; Winder and Jassby 2011).
