---
title: "Benthic Invertebrates Background"
---

Benthic organisms are creatures that live at the bottom of water bodies. This includes invertebrates (animals without backbones) like clams, shrimp, crabs, worms, aquatic insects, and small crustaceans called amphipods. Some benthic organisms live in or on the soft mud of the San Francisco Estuary, while others attach themselves to rocks and other hard surfaces. There are also benthic vertebrates (animals with backbones) that include various fish species.

Benthic organisms are a central part of the estuarine food web, consuming and consumed by other creatures. Every winter during low-tides, thousands of migrating shorebirds feast upon uncovered clams, crabs, and worms found in the mudflats. Humans can also take advantage of the low tides to harvest these organisms. Certain fish species, including juvenile salmon, striped bass, and sturgeon, also consume many types of benthic organisms.

A large percentage of the benthic organisms found in the San Francisco Estuary are non-native, and some of these species can have negative effects on the health of the estuary. For example, non-native clams can filter out much of the available phytoplankton, outcompeting the zooplankton who in turn are major sources of fish food. Historically, shrimp supported a large commercial fishery in San Francisco Estuary, and California’s commercial Dungeness crab fishery still depends upon crabs that spend the first two years of their life growing in the San Francisco Estuary.

Changes in benthic organisms’ populations can be indications of larger changes in the physical conditions and water quality of the San Francisco Estuary, including alterations in pollution levels, freshwater inflows, salinity, and sediment composition.
